# Generated by Django 4.1 on 2022-08-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanagent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
